### ISSUE TITLE
Potential improvement to bibtex formatting 

### ISSUE THREAD

**Issue by alexgoodell** [andrewning/alfred-workflows-scientific#10]
https://github.com/andrewning/alfred-workflows-scientific/blob/67ba4c3ec28d491af9e3c1606672e11b54908330/reference-importer/src/doi.py#L29

There are a few [different ways to get bibtex from doi.org](https://stackoverflow.com/a/40311057/1513646). For articles with special characters, the pure bibtex options has some annoying formatting issues. I prefer this version:

```python
headers = {'Accept': 'text/bibliography; style=bibtex'}
```

**Comment by andrewning** [comment]
thanks.  I've fixed this.
