### ISSUE TITLE
ref importer stopped working for me today

### ISSUE THREAD

**Issue by tobiasgerstenberg** [andrewning/alfred-workflows-scientific#11]
- it still worked yesterday and i haven't installed any updates in the meantime
- i'm on alfred v3.6.1

**Comment by tobiasgerstenberg** [comment]
maybe this is helpful/relevant? https://gist.github.com/fredcallaway/8deebaabd652a06b5105450588d0d1b1

**Comment by andrewning** [comment]
The regular ref command?  It's still working for me on 3.6.1.  Maybe crossref was momentarily down?

That gist was for a fix with gsref.  Google Scholar doesn't actually have an API so I was relying on screen scraping, but google keeps changing things that break the script (including what's in that gist).  I've stopped supporting google scholar, but the regular ref command should work.

**Comment by tobiasgerstenberg** [comment]
works for me again, too. it was probably just crossref being down. thanks for the quick response!
