### ISSUE TITLE
Final step of reference import not working

### ISSUE THREAD

**Issue by mjknght** [andrewning/alfred-workflows-scientific#15]
Sorry for the vague description of this issue but: in Bibdesk 1.7.5 the final step of the reference import appears to have stopped working. The record is copied to the clipboard, and the app pops up, but I have to then paste the record to finish the job. It was working for me prior to this update.

Thanks in advance for any help!

Mark

**Comment by andrewning** [comment]
Yeah, I've noticed also.  Something in Bibdesk is changed, perhaps a bug.  I looked into the applescript dictionary and the current command should work.  Hopefully it will be resolved with a BibDesk update.  For now you can finish the last step by selecting "new publication from clipboard" or option-cmd-L in BibDesk.  The reference is already in the clipboard and BibDesk will be activated already.

**Comment by mjknght** [comment]
Thanks for this response, and for the workaround!

**Comment by andrewning** [comment]
looks like it works again with the latest version of BibDesk.

**Comment by mjknght** [comment]
So it does! Thanks for taking the time to let me know. Much appreciated.
