### ISSUE TITLE
Reference Importer skips to standard wikipedia search

### ISSUE THREAD

**Issue by jwbullard** [andrewning/alfred-workflows-scientific#18]
When I initiate a reference search in Alfred 4 using the Reference Importer Workflow, the workflow is recognized, but as soon as I hit space and start typing a search term the options go to the standard Wikipedia, Amazon, google (see screenshots).
<img width="764" alt="Screen Shot 2022-02-22 at 11 10 46 AM" src="https://user-images.githubusercontent.com/62448796/155183034-e6f7b414-2914-4287-b474-01590b930618.png">
<img width="764" alt="Screen Shot 2022-02-22 at 11 11 08 AM" src="https://user-images.githubusercontent.com/62448796/155183090-084e1172-c5ab-4316-91b0-bf6b549ab37c.png">

**Comment by bcdavasconcelos** [comment]
To start figuring out what is wrong, you need to check the Debug pane and at least copy and paste the results you are getting. See the Alfred documentation to find it.

**Comment by emraher** [comment]
Have you checked https://github.com/andrewning/alfred-workflows-scientific/issues/17#issuecomment-850847768 and https://github.com/andrewning/alfred-workflows-scientific/issues/17#issuecomment-912063594 ?

**Comment by jwbullard** [comment]
Thanks very much for those comments.

@emraher  I have now used your updated version with the slight fix suggested by @soto97 and everything is working really well.  I'm not seeing the references I expect to see in the list that gets produced, but at least I'm not getting any errors.

@bcdavasconcelos I will use the debug pane and paste the results in the future.  Thanks for pointing that out.
